/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.NCC.Suvha_Shrestha_150013.Board_game.view;

/**
 *
 * @author Suvha
 */
import edu.NCC.Suvha_Shrestha_150013.Board_game.CRUDcontrol.CRUDImpl.CRUDImpl;
import edu.NCC.Suvha_Shrestha_150013.Board_game.CRUDcontrol.CRUDcontrol;
import edu.NCC.Suvha_Shrestha_150013.Board_game.DBConnection.dbConnection;
import edu.NCC.Suvha_Shrestha_150013.Board_game.entity.gameDetailList;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class gameDetails extends javax.swing.JFrame {
    private dbConnection conn=new dbConnection();
    CRUDcontrol CrudControl=new CRUDImpl();
    public gameDetails() {
        initComponents();
        fillcomboCategory();
    }
     public void CleartextFeild(){
        txt_game_name.setText("");
        txt_game_designer.setText("");
        txt_minimum_player.setText("");
        txt_maximum_player.setText("");
        txt_optimal_player.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_game_details = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_game_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_game_designer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_minimum_player = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_maximum_player = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_optimal_player = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_cataegory = new javax.swing.JComboBox();
        btn_new_category = new javax.swing.JButton();
        jp_gameDetail_controller = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Game Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name of game: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Game designer: ");

        txt_game_designer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_game_designerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Minimum player: ");

        txt_minimum_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_minimum_playerActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Maximum player: ");

        txt_maximum_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maximum_playerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Optimal player: ");

        txt_optimal_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_optimal_playerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Game category: ");

        cmb_cataegory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cataegoryActionPerformed(evt);
            }
        });

        btn_new_category.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_new_category.setText("New Category");
        btn_new_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_categoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_game_detailsLayout = new javax.swing.GroupLayout(jp_game_details);
        jp_game_details.setLayout(jp_game_detailsLayout);
        jp_game_detailsLayout.setHorizontalGroup(
            jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_game_detailsLayout.createSequentialGroup()
                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_game_detailsLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_game_detailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_game_detailsLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_game_designer, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_game_detailsLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_game_name, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_game_detailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_game_detailsLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_minimum_player, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_game_detailsLayout.createSequentialGroup()
                                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_optimal_player, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_maximum_player, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_game_detailsLayout.createSequentialGroup()
                                        .addComponent(cmb_cataegory, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_new_category)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_game_detailsLayout.setVerticalGroup(
            jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_game_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_game_name, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_game_designer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jp_game_detailsLayout.createSequentialGroup()
                        .addComponent(txt_minimum_player, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maximum_player, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_optimal_player, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jp_game_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_cataegory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_new_category))
                .addContainerGap())
        );

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_gameDetail_controllerLayout = new javax.swing.GroupLayout(jp_gameDetail_controller);
        jp_gameDetail_controller.setLayout(jp_gameDetail_controllerLayout);
        jp_gameDetail_controllerLayout.setHorizontalGroup(
            jp_gameDetail_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_gameDetail_controllerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addGap(69, 69, 69))
        );
        jp_gameDetail_controllerLayout.setVerticalGroup(
            jp_gameDetail_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_gameDetail_controllerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jp_gameDetail_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_close))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_game_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_gameDetail_controller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_game_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_gameDetail_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_game_designerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_game_designerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_game_designerActionPerformed

    private void txt_minimum_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_minimum_playerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_minimum_playerActionPerformed

    private void txt_maximum_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maximum_playerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maximum_playerActionPerformed

    private void txt_optimal_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_optimal_playerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_optimal_playerActionPerformed

    private void cmb_cataegoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cataegoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cataegoryActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        gameDetailList gamelist= new gameDetailList();
        gamelist.setGameName(txt_game_name.getText());
        gamelist.setGameDesigner(txt_game_designer.getText());
        gamelist.setMinimum_player(Integer.parseInt(txt_minimum_player.getText()));
        gamelist.setMaximum_player(Integer.parseInt(txt_maximum_player.getText()));
        gamelist.setOptimal_player(Integer.parseInt(txt_optimal_player.getText()));
        gamelist.setGameCategory(cmb_cataegory.getSelectedItem().toString());
        CrudControl.insertGameDetail(gamelist);
        CleartextFeild();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_new_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_categoryActionPerformed
          GameCategory gameC =new GameCategory();
          gameC.setVisible(true);
          
    }//GEN-LAST:event_btn_new_categoryActionPerformed
    public void fillcomboCategory(){
         conn.opendbConnection();
           try{
              
                String qry="SELECT * FROM `game_category`";
            PreparedStatement pstmt=conn.initStatement(qry);
           ResultSet res=conn.executeQuery();
            while(res.next()){
                String gameList=res.getString("game_category");
                
                cmb_cataegory.addItem(gameList);
            
            }
            conn.closeCOnnection();
    }
           catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
}
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_new_category;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox cmb_cataegory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jp_gameDetail_controller;
    private javax.swing.JPanel jp_game_details;
    private javax.swing.JTextField txt_game_designer;
    private javax.swing.JTextField txt_game_name;
    private javax.swing.JTextField txt_maximum_player;
    private javax.swing.JTextField txt_minimum_player;
    private javax.swing.JTextField txt_optimal_player;
    // End of variables declaration//GEN-END:variables
}
