/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.NCC.Suvha_Shrestha_150013.Board_game.view;

import edu.NCC.Suvha_Shrestha_150013.Board_game.CRUDcontrol.CRUDImpl.CRUDImpl;
import edu.NCC.Suvha_Shrestha_150013.Board_game.CRUDcontrol.CRUDcontrol;
import edu.NCC.Suvha_Shrestha_150013.Board_game.DBConnection.dbConnection;
import edu.NCC.Suvha_Shrestha_150013.Board_game.entity.gameDetailList;
import edu.NCC.Suvha_Shrestha_150013.Board_game.entity.playerDetailList;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Suvha
 */
public final class playerDashboard extends javax.swing.JFrame {
    private dbConnection conn= new dbConnection();
    CRUDcontrol crudControl=new CRUDImpl();
 
    private final playerDetailList playername;
    /**
     * Creates new form playerDashboard
     */
    public playerDashboard(playerDetailList playername) {
        
        this.playername = playername;
        initComponents();
        fillcomboLocation();
        fillcomboBookmarkList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmb_location = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_timeShot_from = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_timeShot_to = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_playerList = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txt_game_name = new javax.swing.JTextField();
        btn_search_game_name = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_bookmark_name = new javax.swing.JTextField();
        btn_add_bookmark = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmb_bookmarkList = new javax.swing.JComboBox();
        btn_view_bookmark = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_num_player = new javax.swing.JTextField();
        btn_edit_user_profile = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmb_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_locationActionPerformed(evt);
            }
        });

        jLabel2.setText("Search by Location:");

        jLabel3.setText("   Time shot  (Enter value in 24 hour format)");

        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel4.setText("From");

        txt_timeShot_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timeShot_fromActionPerformed(evt);
            }
        });

        jLabel5.setText("To");

        jTextArea_playerList.setColumns(20);
        jTextArea_playerList.setRows(5);
        jScrollPane1.setViewportView(jTextArea_playerList);

        jLabel6.setText("Enter game name:");

        txt_game_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_game_nameActionPerformed(evt);
            }
        });

        btn_search_game_name.setText("SEARCH");
        btn_search_game_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_game_nameActionPerformed(evt);
            }
        });

        jLabel7.setText("Name of Bookmark: ");

        btn_add_bookmark.setText("Add Bookmark");
        btn_add_bookmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_bookmarkActionPerformed(evt);
            }
        });

        jLabel8.setText("View Bookmark:");

        btn_view_bookmark.setText("View");
        btn_view_bookmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_bookmarkActionPerformed(evt);
            }
        });

        jLabel1.setText("Number of player: ");

        btn_edit_user_profile.setText("Edit Profile");
        btn_edit_user_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_edit_user_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_user_profileActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*Works only otimal player num is false.*");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*Shows bookmark if added*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_edit_user_profile)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_add_bookmark)
                                    .addComponent(btn_view_bookmark)))
                            .addComponent(txt_bookmark_name, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_bookmarkList, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_location, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_timeShot_from, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_timeShot_to, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_num_player, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_search_game_name)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_game_name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_edit_user_profile)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_location, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_timeShot_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_timeShot_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_search)
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num_player, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_game_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btn_search_game_name)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_bookmark_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add_bookmark))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_bookmarkList, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_view_bookmark)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timeShot_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timeShot_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeShot_fromActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
      cleartext();
      
       playerDetailList playerDL =new playerDetailList();
        playerDL.setPlayer_location(cmb_location.getSelectedItem().toString());
        playerDL.setPlayer_name(playername.getPlayer_name());
        
           if(txt_timeShot_from.getText().isEmpty() || txt_timeShot_to.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Please enter the value", "ERROR", JOptionPane.ERROR_MESSAGE);
         }else{
                   playerDL.setAvailableTime_from(Integer.parseInt(txt_timeShot_from.getText()));
                   
                playerDL.setAvailableTime_to(Integer.parseInt(txt_timeShot_to.getText()));
           }
     try{
       jTextArea_playerList.setText(crudControl.searchplayer(playerDL));
      }catch(ClassNotFoundException | SQLException | NumberFormatException ex ){
         JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE); 
      }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void cmb_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_locationActionPerformed

    private void btn_search_game_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_game_nameActionPerformed
        cleartext();
        playerDetailList playerDL =new playerDetailList();
            gameDetailList gameDL=new gameDetailList();
            if(!(txt_num_player.getText().equals(""))){
                  playerDL.setPlayer_number(Integer.parseInt(txt_num_player.getText()));
            }
            gameDL.setGameName(txt_game_name.getText());
            jTextArea_playerList.setText(crudControl.searchGame(gameDL, playerDL));
    }//GEN-LAST:event_btn_search_game_nameActionPerformed

    private void btn_add_bookmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_bookmarkActionPerformed
      playerDetailList playerDL=new playerDetailList();
      playerDL.setAddBookmark(txt_bookmark_name.getText());
      crudControl.addBookmark(playerDL);
    }//GEN-LAST:event_btn_add_bookmarkActionPerformed

    private void btn_view_bookmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_bookmarkActionPerformed
        cleartext();
        playerDetailList playerDL=new playerDetailList();
        playerDL.setAddBookmark(cmb_bookmarkList.getSelectedItem().toString());
        System.out.println(cmb_bookmarkList.getSelectedItem().toString());
        jTextArea_playerList.setText(crudControl.viewBookmark(playerDL));
    }//GEN-LAST:event_btn_view_bookmarkActionPerformed

    private void txt_game_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_game_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_game_nameActionPerformed

    private void btn_edit_user_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_user_profileActionPerformed
       EditPlayerDetail editPlayer = new EditPlayerDetail(playername.getPlayer_name());
       editPlayer.setVisible(true);
    }//GEN-LAST:event_btn_edit_user_profileActionPerformed

   
    
   public void fillcomboLocation(){
                   conn.opendbConnection();
           try{
              
                String qry="SELECT * FROM `player_details`";
            PreparedStatement pstmt=conn.initStatement(qry);
           ResultSet res=conn.executeQuery();
            while(res.next()){
                String gameList=res.getString("player_location");
                
                cmb_location.addItem(gameList);
            
            }
            conn.closeCOnnection();
    }
           catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
}
          
   }
  public void fillcomboBookmarkList(){
              conn.opendbConnection();
           try{
              
                String qry="SELECT * FROM `bookmark` WHERE player_name='"+playername.getPlayer_name()+"'";
            PreparedStatement pstmt=conn.initStatement(qry);
           ResultSet res=conn.executeQuery();
            while(res.next()){
                String gameList=res.getString("bookmark_name");
                cmb_bookmarkList.addItem(gameList);
            
            }
            conn.closeCOnnection();
    }
           catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
  }
  }
   private void cleartext(){
               jTextArea_playerList.setText("");
           }
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_bookmark;
    private javax.swing.JButton btn_edit_user_profile;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search_game_name;
    private javax.swing.JButton btn_view_bookmark;
    private javax.swing.JComboBox cmb_bookmarkList;
    private javax.swing.JComboBox cmb_location;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_playerList;
    private javax.swing.JTextField txt_bookmark_name;
    private javax.swing.JTextField txt_game_name;
    private javax.swing.JTextField txt_num_player;
    private javax.swing.JTextField txt_timeShot_from;
    private javax.swing.JTextField txt_timeShot_to;
    // End of variables declaration//GEN-END:variables
}
